### ISSUE TITLE
Can add movie with director's invalid birthday data format

### ISSUE THREAD

**Issue by GreedlyCore** [vasil1y-777/lab5#12]
![image](https://user-images.githubusercontent.com/59867043/222925249-f797ea01-3d29-45f0-a14b-5339fd3fd31c.png)

**Comment by GreedlyCore** [comment]
![image](https://user-images.githubusercontent.com/59867043/227800302-90adec3b-7675-413e-9706-d1071b6d940b.png)

**Comment by Nikulin-V** [comment]
Fixed at [commit 59da323](https://github.com/vasil1y-777/lab5/commit/59da32323151e092742a8dcbd19f1584afa3b486)
