### ISSUE TITLE
Add validator for file extencions (specifically ".xml") when input files via console arguments

### ISSUE THREAD

**Issue by GreedlyCore** [vasil1y-777/lab5#25]
Main.java 
![image](https://user-images.githubusercontent.com/59867043/224810432-c3919bf4-0c3e-49b6-a7d3-4970e2c305fa.png)

**Comment by Nikulin-V** [comment]
Fixed at [commit 6e118cb](https://github.com/vasil1y-777/lab5/commit/6e118cbca6834a51925d9a38cf01fab9453a2d7a)
